spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: test
  name: test-YAML
  environment: testing
  enabled: false
  servers:
    - www.abc.test.com
    - www.xyz.test.com

spring:
  config:
    activate:
      on-profile: prod
  name: prod-YAML
  environment: production
  enabled: true
  servers:
    - www.abc.com
    - www.xyz.com
